### ISSUE TITLE
client request returns null

### ISSUE THREAD

**Issue by NilsFrkal** [zbjornson/ndns#6]
Hi. 

I did an npm update on this package and suddenly the call c_req = client.request() returns null. I re-tested by reverting back to the previous bindns code base without changing my server.js and it works again. NPM update and again response is null. Please let me know if you need any more details.

Thank you very much.

Nils

**Comment by zbjornson** [comment]
Hi Nils, can you provide the SHAs for the working and non-working commits please? Should say in your lock file. I can't repro the error locally.

**Comment by NilsFrkal** [comment]
Hi.

Working commit:

    "bindns": {
      "version": "github:primitybio/bindns#ada38460dbee4e19ab2e0065171bbeb4aa961de3",
      "from": "github:primitybio/bindns"
    },

Attached also the package.json from the working commit (within the bindns folder).

The non-working commit:

    "bindns": {
      "version": "github:primitybio/bindns#42d5644952a18eeebeceb0fc82bdf898ba9be265",
      "from": "github:primitybio/bindns"
    },

As an additional info the c_res call goes to an nginx proxy which forwards the dns request to the google dns server. The nginx runs in a docker container. Not sure if this helps  .. but I could replicate the behaviour on both my dev server (local) and prod instance (AWS EC2).

Best, Nils

**Comment by zbjornson** [comment]
Thanks! When you say that line "returns null", do you mean the argument provided to the request callback? In 92dfaf1 I changed the callback arguments so that the first arg is the error (which may be null) and second arg is the response. See example:

https://github.com/primitybio/bindns/blob/42d5644952a18eeebeceb0fc82bdf898ba9be265/examples/simple-client.js#L15-L21

Sorry for the breaking change. I should publish this module to npm or at least start making GitHub releases so the changelog becomes easier to read.

**Comment by NilsFrkal** [comment]
Oh brilliant, yes, that’s probably it. Will test it now.

 

Best, Nils

**Comment by NilsFrkal** [comment]
I can confirm it works. Will close the issue. Thank you very much.

**Comment by NilsFrkal** [comment]
Answer above solves the issue. Thank you.
